# Define the resources
resources:
- name: cf
  type: cf
  source:
    api: << edit Cloud Foundry API >>
    username: ((cf-username))
    password: ((cf-password))
    organization: << edit orgs >>
    space: << edit space >>

# Define the jobs
jobs:
- name: check-all-apps
  plan:
  - get: cf

  - task: check-java-version-in-apps
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-cli
      run:
        path: bash
        args:
        - -c
        - |
          cf api ((cf-api)) --skip-ssl-validation
          cf auth ((cf-username)) ((cf-password))
          cf target -o ((cf-organization)) -s ((cf-space))

          apps=$(cf curl "/v3/apps?space_guids=$(cf space ((cf-space)) --guid)&fields[buildpacks]=name")

          for app in $(echo "$apps" | jq -r '.resources[] | @base64'); do
            _jq() {
              echo ${app} | base64 --decode | jq -r ${1}
            }

            app_name=$(_jq '.name')
            app_buildpack=$(_jq '.lifecycle.data.buildpacks[0]')

            echo "App name: $app_name"
            echo "App buildpack: $app_buildpack"

            if [[ $app_buildpack == *java* ]]; then
              echo "App is using Java"

              java_version=$(cf ssh $app_name -c "JAVA_HOME=.java-buildpack/open_jdk_jre java -version 2>&1")

              echo "Java version:"
              echo "$java_version"

            else
              echo "App is not using Java"
            fi

            echo ""
          done
